version: "3"
services:
  database:
    container_name: deportivo-carolina-db
    image: amazon/dynamodb-local
    ports:
      - "${DYNAMODB_PORT}:8000"
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./.dynamodb/database:/data/db
