version: "3"
services:
  database:
    container_name: deportivo-carolina-db
    image: amazon/dynamodb-local
    ports:
      - "${DYNAMODB_PORT}:8000"
    volumes:
      - ./.dynamodb/database:/data/db
