#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./node_modules/.bin/prettier '**/*.js' --single-quote --trailing-comma es5 --write
./node_modules/.bin/eslint backend --ignore-pattern 'public/' --fix
./node_modules/.bin/eslint frontend --ignore-pattern 'public/' --ignore-pattern 'build/' --fix
git add .
